version: '3.7'
networks:
  localnet:
volumes:
  db_data:
services:
  backend:
    image: sherifsadek/tracker_backend:33
    container_name: back
    ports:
    - "8500:8081"
    networks:
    - localnet
  db:
    image: postgres:14-alpine
    container_name: pg14
    ports:
    - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: pdwrkstn
      POSTGRES_USER: panorama
      POSTGRES_DB: tracker
    networks:
    - localnet