apiVersion: apps/v1
kind: Deployment                                          
metadata:
  name: tracker-backend
  labels:
    app: tracker-backend
spec:
  selector:
    matchLabels:
      app: tracker-backend
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: tracker-backend                                 
    spec:
      containers:
        - image: sherifsadek/tracker_backend:24
          imagePullPolicy: IfNotPresent
          name: tracker-backend
          ports:
            - containerPort: 8081
          env:
          - name: POSTGRES_PASSWORD
            value: pdwrkstn
          - name: POSTGRES_USER
            value: panorama
          - name: POSTGRES_DB
            value: tracker
