apiVersion: v1
kind: Service              
metadata:
  name: tracker-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000              
    protocol: TCP          
    targetPort: 3000        
  selector:                
    app: tracker-frontend     
