apiVersion: v1
kind: Service              
metadata:
  name: tracker-backend-service
spec:
  type: LoadBalancer
  ports:
  - port: 8500              
    protocol: TCP          
    targetPort: 8081        
  selector:                
    app: tracker-backend    
