apiVersion: v1
kind: Service              
metadata:
  name: tracker-db-service
spec:
  type: LoadBalancer
  ports:
  - port: 5432              
    protocol: TCP          
    targetPort: 5432        
  selector:                
    app: tracker-db      
